package db

import (
	"context"
	"database/sql"
	"time"

	"bohack_backend_go/internal/config"
)

var schemaStatements = []string{
	`
	CREATE TABLE IF NOT EXISTS users (
		uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		username varchar(50) NOT NULL UNIQUE,
		email varchar(255) NOT NULL UNIQUE,
		password_hash varchar(255) NOT NULL,
		avatar_url varchar(500),
		bio text,
		phone varchar(32),
		is_admin boolean NOT NULL DEFAULT false,
		role varchar(20) NOT NULL DEFAULT 'visitor',
		bk_balance numeric(10, 2) NOT NULL DEFAULT 0.00,
		team_id integer,
		created_at timestamp without time zone NOT NULL,
		updated_at timestamp without time zone NOT NULL
	)
	`,
	`CREATE INDEX IF NOT EXISTS idx_users_team_id ON users(team_id)`,
	`CREATE INDEX IF NOT EXISTS idx_users_role ON users(role)`,
	`
	CREATE TABLE IF NOT EXISTS verification_codes (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		email varchar(255) NOT NULL,
		code_type varchar(50) NOT NULL DEFAULT 'register',
		code char(6) NOT NULL,
		expires_at timestamp without time zone NOT NULL,
		last_send_at timestamp without time zone NOT NULL,
		UNIQUE(email, code_type)
	)
	`,
	`CREATE INDEX IF NOT EXISTS idx_verification_codes_email ON verification_codes(email)`,
	`CREATE INDEX IF NOT EXISTS idx_verification_codes_code_type ON verification_codes(code_type)`,
	`CREATE INDEX IF NOT EXISTS idx_verification_codes_expires_at ON verification_codes(expires_at)`,
	`
	CREATE TABLE IF NOT EXISTS events (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		slug varchar(100) NOT NULL UNIQUE,
		title varchar(255) NOT NULL,
		status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
		is_current boolean NOT NULL DEFAULT false,
		registration_open_at timestamp without time zone,
		registration_close_at timestamp without time zone,
		created_at timestamp without time zone NOT NULL,
		updated_at timestamp without time zone NOT NULL
	)
	`,
	`ALTER TABLE events ADD COLUMN IF NOT EXISTS is_current boolean NOT NULL DEFAULT false`,
	`CREATE INDEX IF NOT EXISTS idx_events_status ON events(status)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_events_single_current ON events (is_current) WHERE is_current`,
	`
	CREATE TABLE IF NOT EXISTS event_registrations (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		event_id bigint NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
		user_id integer NOT NULL REFERENCES users(uid) ON DELETE RESTRICT,
		status varchar(20) NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'cancelled')),
		real_name varchar(100) NOT NULL,
		phone varchar(32) NOT NULL,
		email_snapshot varchar(255) NOT NULL,
		school varchar(255),
		company varchar(255),
		bio text,
		team_name varchar(255),
		role_preference varchar(50),
		source varchar(100),
		note text,
		extra jsonb NOT NULL DEFAULT '{}'::jsonb,
		submitted_at timestamp without time zone NOT NULL,
		reviewed_at timestamp without time zone,
		reviewed_by integer REFERENCES users(uid) ON DELETE SET NULL,
		review_note text,
		created_at timestamp without time zone NOT NULL,
		updated_at timestamp without time zone NOT NULL,
		UNIQUE(event_id, user_id)
	)
	`,
	`CREATE INDEX IF NOT EXISTS idx_event_registrations_event_status ON event_registrations(event_id, status)`,
	`CREATE INDEX IF NOT EXISTS idx_event_registrations_user_id ON event_registrations(user_id)`,
	`
	CREATE TABLE IF NOT EXISTS event_registration_attachments (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		registration_id bigint NOT NULL REFERENCES event_registrations(id) ON DELETE CASCADE,
		kind varchar(50) NOT NULL,
		file_url text NOT NULL,
		file_name varchar(255) NOT NULL,
		mime_type varchar(100) NOT NULL,
		file_size bigint NOT NULL DEFAULT 0,
		created_at timestamp without time zone NOT NULL
	)
	`,
	`ALTER TABLE event_registration_attachments ADD COLUMN IF NOT EXISTS file_size bigint NOT NULL DEFAULT 0`,
	`CREATE INDEX IF NOT EXISTS idx_registration_attachments_registration_id ON event_registration_attachments(registration_id)`,
}

func EnsureSchema(ctx context.Context, db *sql.DB, cfg config.Config) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	for _, stmt := range schemaStatements {
		if _, err := tx.ExecContext(ctx, stmt); err != nil {
			return err
		}
	}

	now := time.Now().UTC()
	if _, err := tx.ExecContext(
		ctx,
		`
		INSERT INTO events (slug, title, status, is_current, created_at, updated_at)
		VALUES ($1, $2, 'published', false, $3, $3)
		ON CONFLICT (slug) DO NOTHING
		`,
		cfg.DefaultEventSlug,
		cfg.DefaultEventTitle,
		now,
	); err != nil {
		return err
	}

	if _, err := tx.ExecContext(
		ctx,
		`
		UPDATE events
		SET is_current = true,
			updated_at = $2
		WHERE slug = $1
		  AND NOT EXISTS (
			SELECT 1
			FROM events
			WHERE is_current = true
		  )
		`,
		cfg.DefaultEventSlug,
		now,
	); err != nil {
		return err
	}

	return tx.Commit()
}
